name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        description: Build working directory
        type: string
        default: .
      dockerfile:
        description: Dockerfile path
        type: string
        default: Dockerfile
      image-name:
        description: Docker image name
        type: string
        required: true
      image-tags:
        description: Docker image tags (newline separated)
        type: string
        required: true

jobs:
  build:
    name: Build image
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-slug: linux-amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform-slug: linux-arm64

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v6

      - name: Set up Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push digest
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          tags: ${{ inputs.image-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Output digest
        id: output-digest
        uses: GoCodeAlone/github-action-matrix-outputs-write@1.0.3
        with:
          matrix-step-name: build
          matrix-key: ${{ matrix.platform-slug }}
          outputs: |
            digest: ${{ steps.build-and-push.outputs.digest }}

  push-tags:
    name: Push tags
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10

    steps:
      - name: Set up Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Get digests
        id: get-digests
        uses: GoCodeAlone/github-action-matrix-outputs-read@1.0.6
        with:
          matrix-step-name: build

      - name: Login to Dockerhub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push tags
        id: push-tags
        run: |
          TAGS_FLAGS=""
          while read -r TAG; do
            [ -z "$TAG" ] && continue
            TAGS_FLAGS="$TAGS_FLAGS -t $IMAGE_NAME:$TAG"
          done <<<"$TAGS_INPUT"

          DIGESTS=$(
            echo "$DIGESTS_JSON" |
            jq -r --arg IMAGE_NAME "$IMAGE_NAME" \
              '.digest | to_entries[] | "\($IMAGE_NAME)@\(.value)"'
          )

          docker buildx imagetools create \
            $TAGS_FLAGS \
            $DIGESTS

          echo "
          Tags: $TAGS_INPUT
          Digests: $DIGESTS
          "
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
          DIGESTS_JSON: ${{ steps.get-digests.outputs.result }}
          TAGS_INPUT: ${{ inputs.image-tags }}
